plugins {
	id "fabric-loom" version "1.8.+"
	id "maven-publish"
	id "com.github.johnrengelman.shadow" version "8.1.1"
}

base.archivesName = archives_base_name
group = project.maven_group

// Formats the mod version to include the Minecraft version and build number (if present)
// example: 1.0.0+1.18.2-build.100
String buildNumber = System.getenv("GITHUB_RUN_NUMBER")
version = "$mod_version+$minecraft_version" + (buildNumber != null ? "-build.$buildNumber" : "")

repositories {
	maven { url = "https://maven.parchmentmc.org" }

	maven { url = "https://mvn.devos.one/releases" }
	maven { url = "https://mvn.devos.one/snapshots" }
	maven { url = "https://modmaven.dev/" }
	maven { url = "https://maven.jamieswhiteshirt.com/libs-release" }
	maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven" }

	maven {
		url = "https://jitpack.io/"
		content { includeGroupAndSubgroups("com.github") }
	}

	maven { url = "https://maven.shedaniel.me" }
	maven { url = "https://maven.blamejared.com" }
	maven { url = "https://maven.terraformersmc.com/releases" }
	maven { url = "https://maven.createmod.net" }
	maven { url = "https://maven.engine-room.dev/releases" }

	mavenCentral()
}

configurations.configureEach {
	resolutionStrategy {
		// make sure the desired version of loader is used. Sometimes old versions are pulled in transitively.
		force("net.fabricmc:fabric-loader:$fabric_loader_version")
	}
}

dependencies {
	// Setup
	minecraft("com.mojang:minecraft:$minecraft_version")
	mappings(loom.layered {
		it.officialMojangMappings { nameSyntheticMembers = false }
		it.parchment("org.parchmentmc.data:parchment-$minecraft_version:$parchment_version@zip")
	})
	modImplementation("net.fabricmc:fabric-loader:$fabric_loader_version")

	// dependencies
	modImplementation("net.fabricmc.fabric-api:fabric-api:$fabric_api_version")

	// Create - dependencies are added transitively
	modImplementation("com.simibubi.create:create-fabric:${create_version}")

	// Development QOL
	modLocalRuntime("com.terraformersmc:modmenu:$modmenu_version")

	// Recipe Viewers - Create Fabric supports JEI, REI, and EMI.
	// See root gradle.properties to choose which to use at runtime.
	switch (recipe_viewer.toLowerCase(Locale.ROOT)) {
		case "jei": modLocalRuntime("mezz.jei:jei-$minecraft_version-fabric:$jei_version"); break
		case "rei": modLocalRuntime("me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"); break
		case "emi": modLocalRuntime("dev.emi:emi-fabric:$emi_version"); break
		case "disabled": break
		default: println("Unknown recipe viewer specified: $recipe_viewer. Must be JEI, REI, EMI, or disabled.")
	}
	shadow(implementation("io.undertow:undertow-core:2.2.24.Final"))
	shadow(implementation("org.jboss.logging:jboss-logging:3.4.3.Final"))
	shadow(implementation("org.jboss.threads:jboss-threads:3.5.0.Final"))
	shadow(implementation("org.jboss.xnio:xnio-api:3.8.16.Final"))
	shadow(implementation("org.jboss.xnio:xnio-nio:3.8.16.Final"))
	shadow(implementation("org.wildfly.common:wildfly-common:1.5.4.Final"))
	shadow(implementation("org.wildfly.client:wildfly-client-config:1.0.1.Final"))

// Jackson
	shadow(implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2"))
	shadow(implementation("com.fasterxml.jackson.core:jackson-core:2.15.2"))
	shadow(implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.2"))

	shadow(implementation("org.tomlj:tomlj:1.1.1"))
}

processResources {
	// require dependencies to be the version compiled against or newer
	Map<String, Object> properties = [
			"version": version,
			"fabric_loader_version": fabric_loader_version,
			"fabric_api_version": fabric_api_version,
			"create_version": create_version,
			"minecraft_version": minecraft_version
	]

	inputs.properties(properties)

	filesMatching("fabric.mod.json") {
		expand properties
	}
}

java {
	withSourcesJar()
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}" }
	}
}

shadowJar {
	configurations = [project.configurations.shadow]
	archiveClassifier.set("dev")
}

remapJar {
	dependsOn(shadowJar)
	inputFile = tasks.shadowJar.archiveFile
}
